spring.jpa.hibernate.ddl-auto=create-drop
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
spring.docker.compose.enabled=true
debug.allow-all-tokens=
google.client-id=
jwt.secret=
