spring.jpa.hibernate.ddl-auto=update
logging.level.root=INFO
server.error.whitelabel.enabled=false
server.tomcat.threads.max=50
server.tomcat.threads.min-spare=5
debug.allow-all-tokens=false
google.client-id=
jwt.secret=
frontend.origin=

